[orderApi]
host = "http://138.68.71.39"
# host = "http://order-api-dev"
port = 3000

[soundFiles]
path = "/go/soundfiles/"
# path = "C:/Users/Laptop/Desktop/project-env/code-restaurant-order/ro-analyze-api/soundfiles/"
type = "wav"