noAuthRoutes = ["/soundfile"]

[dev]
    [dev.orderApi]
        host = "http://order-api-dev"
        port = 3000
    [dev.authApi]
        host = "http://auth-api-dev"
        port = 4000
    [dev.soundFiles]
        path = "/go/soundfiles/"
        type = "wav"

[prod]
    [prod.orderApi]
        host = "http://order-api-prod"
        port = 3000
    [prod.authApi]
        host = "http://auth-api-prod"
        port = 4000
    [prod.soundFiles]
        path = "/go/soundfiles/"
        type = "wav"

[local0]
    [local0.orderApi]
        host = "http://138.68.71.39"
        port = 3000
    [local0.soundFiles]
        path = "C:/Users/Laptop/Desktop/project-env/code-restaurant-order/ro-analyze-api/soundfiles/"
        type = "wav"
